--
--  Script    : arch.sql
--  Purpose   : show archived logs generated by hour
--  Tested on : 12c,19c
--
@save_sqp_set

set lines 92 pages 50
col hr          for a20 head 'Hour'
col size_gb     for 99,999,999.999
col archives    for 999,999
ttitle left 'v$archived_log'
SELECT 
     to_char(trunc(COMPLETION_TIME,'HH'),'dd/mm/yyyy HH24:MI:SS')   as hr
    ,thread#
    ,sum(BLOCKS*BLOCK_SIZE)/1024/1024/1024                          as size_gb
    ,count(*)                                                       as archives
FROM 
    gv$archived_log
WHERE 
    trunc(COMPLETION_TIME)=trunc(sysdate)
    AND inst_id=to_number(sys_context('USERENV','INSTANCE'))
GROUP BY 
     trunc(COMPLETION_TIME,'HH')
    ,thread#
ORDER BY 
    1
;

@rest_sqp_set
