--
--  Script    : roles10.sql
--  Purpose   : show roles FROM dba_roles
--  Tested on : 10g,11g
--
@save_sqp_set

set lines 40 pages 50

col role                    for a30 head 'Role'
col oracle_maintained       for a7  head 'OraMnt'
ttitle left 'dba_roles'
SELECT * FROM (
SELECT 
     role
    ,'Y' as oracle_maintained 
FROM 
    dba_roles
WHERE 
    role in ('ADM_PARALLEL_EXECUTE_TASK','APPLICATION_TRACE_VIEWER','AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','AUDIT_ADMIN','AUDIT_VIEWER'
            ,'AUTHENTICATEDUSER','BDSQL_ADMIN','BDSQL_USER','CAPTURE_ADMIN','CDB_DBA','CONNECT','CTXAPP','DATAPATCH_ROLE','DATAPUMP_EXP_FULL_DATABASE'
            ,'DATAPUMP_IMP_FULL_DATABASE','DBA','DBFS_ROLE','DBJAVASCRIPT','DBMS_MDX_INTERNAL','DV_ACCTMGR','DV_ADMIN','DV_AUDIT_CLEANUP'
            ,'DV_DATAPUMP_NETWORK_LINK','DV_GOLDENGATE_ADMIN','DV_GOLDENGATE_REDO_ACCESS','DV_MONITOR','DV_OWNER','DV_PATCH_ADMIN','DV_POLICY_OWNER'
            ,'DV_PUBLIC','DV_REALM_OWNER','DV_REALM_RESOURCE','DV_SECANALYST','DV_STREAMS_ADMIN','DV_XSTREAM_ADMIN','EJBCLIENT','EM_EXPRESS_ALL'
            ,'EM_EXPRESS_BASIC','EXECUTE_CATALOG_ROLE','EXP_FULL_DATABASE','GATHER_SYSTEM_STATISTICS','GDS_CATALOG_SELECT','GGSYS_ROLE'
            ,'GLOBAL_AQ_USER_ROLE','GSMADMIN_ROLE','GSMROOTUSER_ROLE','GSMUSER_ROLE','GSM_POOLADMIN_ROLE','HS_ADMIN_EXECUTE_ROLE','HS_ADMIN_ROLE'
            ,'HS_ADMIN_SELECT_ROLE','IMP_FULL_DATABASE','JAVADEBUGPRIV','JAVAIDPRIV','JAVASYSPRIV','JAVAUSERPRIV','JAVA_ADMIN','JMXSERVER','LBAC_DBA'
            ,'LOGSTDBY_ADMINISTRATOR','OEM_ADVISOR','OEM_MONITOR','OLAP_DBA','OLAP_USER','OLAP_XS_ADMIN','OPTIMIZER_PROCESSING_RATE','ORDADMIN'
            ,'PDB_DBA','PROVISIONER','RDFCTX_ADMIN','RECOVERY_CATALOG_OWNER','RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','RESOURCE'
            ,'SCHEDULER_ADMIN','SELECT_CATALOG_ROLE','SODA_APP','SYSUMF_ROLE','WM_ADMIN_ROLE','XDBADMIN','XDB_SET_INVOKER','XDB_WEBSERVICES'
            ,'XDB_WEBSERVICES_OVER_HTTP','XDB_WEBSERVICES_WITH_PUBLIC','XS_CACHE_ADMIN','XS_CONNECT','XS_NAMESPACE_ADMIN','XS_SESSION_ADMIN'
            ,'DELETE_CATALOG_ROLE','JAVA_DEPLOY','XDBWEBSERVICES','CSW_USR_ROLE','SPATIAL_CSW_ADMIN','CWM_USER','MGMT_USER','OLAPI_TRACE_USER'
            ,'SPATIAL_WFS_ADMIN','WFS_USR_ROLE','ACCHK_READ','MAINTPLAN_APP','NOTIFICATIONS_ADMIN','NOTIFICATIONS_USER'
            )
union all
SELECT 
     role
    ,'N' as oracle_maintained 
FROM 
    dba_roles   
WHERE 
    role not in ('ADM_PARALLEL_EXECUTE_TASK','APPLICATION_TRACE_VIEWER','AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','AUDIT_ADMIN','AUDIT_VIEWER'
                ,'AUTHENTICATEDUSER','BDSQL_ADMIN','BDSQL_USER','CAPTURE_ADMIN','CDB_DBA','CONNECT','CTXAPP','DATAPATCH_ROLE','DATAPUMP_EXP_FULL_DATABASE'
                ,'DATAPUMP_IMP_FULL_DATABASE','DBA','DBFS_ROLE','DBJAVASCRIPT','DBMS_MDX_INTERNAL','DV_ACCTMGR','DV_ADMIN','DV_AUDIT_CLEANUP'
                ,'DV_DATAPUMP_NETWORK_LINK','DV_GOLDENGATE_ADMIN','DV_GOLDENGATE_REDO_ACCESS','DV_MONITOR','DV_OWNER','DV_PATCH_ADMIN','DV_POLICY_OWNER'
                ,'DV_PUBLIC','DV_REALM_OWNER','DV_REALM_RESOURCE','DV_SECANALYST','DV_STREAMS_ADMIN','DV_XSTREAM_ADMIN','EJBCLIENT','EM_EXPRESS_ALL'
                ,'EM_EXPRESS_BASIC','EXECUTE_CATALOG_ROLE','EXP_FULL_DATABASE','GATHER_SYSTEM_STATISTICS','GDS_CATALOG_SELECT','GGSYS_ROLE'
                ,'GLOBAL_AQ_USER_ROLE','GSMADMIN_ROLE','GSMROOTUSER_ROLE','GSMUSER_ROLE','GSM_POOLADMIN_ROLE','HS_ADMIN_EXECUTE_ROLE','HS_ADMIN_ROLE'
                ,'HS_ADMIN_SELECT_ROLE','IMP_FULL_DATABASE','JAVADEBUGPRIV','JAVAIDPRIV','JAVASYSPRIV','JAVAUSERPRIV','JAVA_ADMIN','JMXSERVER','LBAC_DBA'
                ,'LOGSTDBY_ADMINISTRATOR','OEM_ADVISOR','OEM_MONITOR','OLAP_DBA','OLAP_USER','OLAP_XS_ADMIN','OPTIMIZER_PROCESSING_RATE','ORDADMIN'
                ,'PDB_DBA','PROVISIONER','RDFCTX_ADMIN','RECOVERY_CATALOG_OWNER','RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','RESOURCE'
                ,'SCHEDULER_ADMIN','SELECT_CATALOG_ROLE','SODA_APP','SYSUMF_ROLE','WM_ADMIN_ROLE','XDBADMIN','XDB_SET_INVOKER','XDB_WEBSERVICES'
                ,'XDB_WEBSERVICES_OVER_HTTP','XDB_WEBSERVICES_WITH_PUBLIC','XS_CACHE_ADMIN','XS_CONNECT','XS_NAMESPACE_ADMIN','XS_SESSION_ADMIN'
                ,'DELETE_CATALOG_ROLE','JAVA_DEPLOY','XDBWEBSERVICES','CSW_USR_ROLE','SPATIAL_CSW_ADMIN','CWM_USER','MGMT_USER','OLAPI_TRACE_USER'
                ,'SPATIAL_WFS_ADMIN','WFS_USR_ROLE','ACCHK_READ','MAINTPLAN_APP','NOTIFICATIONS_ADMIN','NOTIFICATIONS_USER'
                )
)
ORDER BY
     oracle_maintained DESC
    ,role
;

@rest_sqp_set
