set term off lines 80 pages 500
column inst noprint new_value inst
select 'uu_'||i.instance_name||'_'||i.host_name||'.lst' as inst from v$instance i where i.instance_number=userenv('instance');
spool &&inst

prompt Instance &&inst


break on grantee skip 1
prompt DBA_ROLES_PRIVS for users and roles
select * from dba_role_privs where grantee not in (
                   'SYS',
                   'SYSTEM',
                   'RECOVERY_CATALOG_OWNER',
		   'EXECUTE_CATALOG_ROLE',
		   'SELECT_CATALOG_ROLE',
                   'DBA',
                   'RESOURCE',
                   'CONNECT',
                   'SNMPAGENT',
                   'IMP_FULL_DATABASE',
                   'EXP_FULL_DATABASE',
                   'PERFSTAT',
                   'OUTLN',
                   'DBSNMP',
		   'AQ_USER_ROLE',
		   'HS_ADMIN_ROLE',
		   'WM_ADMIN_ROLE',
		   'CTXAPP',
		   'LBAC_DBA',
                   'AQ_ADMINISTRATOR_ROLE',
		   'AURORA$JIS$UTILITY$',
		   'AURORA$ORB$UNAUTHENTICATED',
		   'BC4J',
		   'CTXSYS',
		   'JAVADEBUGPRIV',
		   'JAVASYSPRIV',
		   'LBACSYS',
		   'MDSYS',
		   'OEM_MONITOR',
		   'OLAPDBA',
		   'OLAPSVR',
		   'OLAPSYS',
		   'OLAP_DBA',
		   'ORDPLUGINS',
		   'ORDSYS',
		   'OSE$HTTP$ADMIN',
		   'RECOVERY_CATALOG_OWNER',
		   'TIMESERIES_DBA',
		   'TIMESERIES_DEVELOPER',
		   'TRACESVR',
		   'WKSYS',
		   'WKUSER',
		   'WKADMIN',
                   'PTRLADM'
                 );

prompt DBA_SYS_PRIVS for users
select * from dba_sys_privs where grantee not in ( 
                   'SYS',
                   'SYSTEM',
                   'RECOVERY_CATALOG_OWNER',
		   'EXECUTE_CATALOG_ROLE',
		   'SELECT_CATALOG_ROLE',
                   'DBA',
                   'RESOURCE',
                   'CONNECT',
                   'SNMPAGENT',
                   'IMP_FULL_DATABASE',
                   'EXP_FULL_DATABASE',
                   'PERFSTAT',
                   'OUTLN',
                   'DBSNMP',
		   'AQ_USER_ROLE',
		   'HS_ADMIN_ROLE',
		   'WM_ADMIN_ROLE',
		   'CTXAPP',
		   'LBAC_DBA',
                   'AQ_ADMINISTRATOR_ROLE',
		   'AURORA$JIS$UTILITY$',
		   'AURORA$ORB$UNAUTHENTICATED',
		   'BC4J',
		   'CTXSYS',
		   'JAVADEBUGPRIV',
		   'JAVASYSPRIV',
		   'LBACSYS',
		   'MDSYS',
		   'OEM_MONITOR',
		   'OLAPDBA',
		   'OLAPSVR',
		   'OLAPSYS',
		   'OLAP_DBA',
		   'ORDPLUGINS',
		   'ORDSYS',
		   'OSE$HTTP$ADMIN',
		   'RECOVERY_CATALOG_OWNER',
		   'TIMESERIES_DBA',
		   'TIMESERIES_DEVELOPER',
		   'TRACESVR',
		   'WKSYS',
		   'WKUSER',
		   'WKADMIN',
                   'PTRLADM'
                 );

col grantee for a15
col table_name for a40
col grantor for a15
col privilege for a15
break on grantee skip 1 on table_name
prompt DBA_TAB_PRIVS for users and roles
select grantee,owner||'.'||table_name as table_name,privilege from dba_tab_privs where grantee not in ( 
                   'SYS',
                   'SYSTEM',
                   'RECOVERY_CATALOG_OWNER',
		   'EXECUTE_CATALOG_ROLE',
		   'SELECT_CATALOG_ROLE',
                   'DBA',
                   'RESOURCE',
                   'CONNECT',
                   'SNMPAGENT',
                   'IMP_FULL_DATABASE',
                   'EXP_FULL_DATABASE',
                   'PERFSTAT',
                   'OUTLN',
                   'DBSNMP',
		   'AQ_USER_ROLE',
		   'HS_ADMIN_ROLE',
		   'WM_ADMIN_ROLE',
		   'CTXAPP',
		   'LBAC_DBA',
                   'AQ_ADMINISTRATOR_ROLE',
		   'AURORA$JIS$UTILITY$',
		   'AURORA$ORB$UNAUTHENTICATED',
		   'BC4J',
		   'CTXSYS',
		   'JAVADEBUGPRIV',
		   'JAVASYSPRIV',
		   'LBACSYS',
		   'MDSYS',
		   'OEM_MONITOR',
		   'OLAPDBA',
		   'OLAPSVR',
		   'OLAPSYS',
		   'OLAP_DBA',
		   'ORDPLUGINS',
		   'ORDSYS',
		   'OSE$HTTP$ADMIN',
		   'RECOVERY_CATALOG_OWNER',
		   'TIMESERIES_DBA',
		   'TIMESERIES_DEVELOPER',
		   'TRACESVR',
		   'WKSYS',
		   'WKUSER',
		   'WKADMIN',
                   'PTRLADM',
		   'PUBLIC'
                 ) and grantee!=grantor;

prompt ALL_TAB_PRIVS_MADE for users and roles
select grantee,owner||'.'||table_name as table_name,privilege from all_tab_privs_made where grantee not in ( 
                   'SYS',
                   'SYSTEM',
                   'RECOVERY_CATALOG_OWNER',
		   'EXECUTE_CATALOG_ROLE',
		   'SELECT_CATALOG_ROLE',
                   'DBA',
                   'RESOURCE',
                   'CONNECT',
                   'SNMPAGENT',
                   'IMP_FULL_DATABASE',
                   'EXP_FULL_DATABASE',
                   'PERFSTAT',
                   'OUTLN',
                   'DBSNMP',
		   'AQ_USER_ROLE',
		   'HS_ADMIN_ROLE',
		   'WM_ADMIN_ROLE',
		   'CTXAPP',
		   'LBAC_DBA',
                   'AQ_ADMINISTRATOR_ROLE',
		   'AURORA$JIS$UTILITY$',
		   'AURORA$ORB$UNAUTHENTICATED',
		   'BC4J',
		   'CTXSYS',
		   'JAVADEBUGPRIV',
		   'JAVASYSPRIV',
		   'LBACSYS',
		   'MDSYS',
		   'OEM_MONITOR',
		   'OLAPDBA',
		   'OLAPSVR',
		   'OLAPSYS',
		   'OLAP_DBA',
		   'ORDPLUGINS',
		   'ORDSYS',
		   'OSE$HTTP$ADMIN',
		   'RECOVERY_CATALOG_OWNER',
		   'TIMESERIES_DBA',
		   'TIMESERIES_DEVELOPER',
		   'TRACESVR',
		   'WKSYS',
		   'WKUSER',
		   'WKADMIN',
                   'PTRLADM',
		   'PUBLIC'
                 ) and grantee!=grantor;

prompt ALL_TAB_PRIVS_RECD for users and roles
select grantee,owner||'.'||table_name as table_name,privilege from all_tab_privs_recd where grantee not in ( 
                   'SYS',
                   'SYSTEM',
                   'RECOVERY_CATALOG_OWNER',
		   'EXECUTE_CATALOG_ROLE',
		   'SELECT_CATALOG_ROLE',
                   'DBA',
                   'RESOURCE',
                   'CONNECT',
                   'SNMPAGENT',
                   'IMP_FULL_DATABASE',
                   'EXP_FULL_DATABASE',
                   'PERFSTAT',
                   'OUTLN',
                   'DBSNMP',
		   'AQ_USER_ROLE',
		   'HS_ADMIN_ROLE',
		   'WM_ADMIN_ROLE',
		   'CTXAPP',
		   'LBAC_DBA',
                   'AQ_ADMINISTRATOR_ROLE',
		   'AURORA$JIS$UTILITY$',
		   'AURORA$ORB$UNAUTHENTICATED',
		   'BC4J',
		   'CTXSYS',
		   'JAVADEBUGPRIV',
		   'JAVASYSPRIV',
		   'LBACSYS',
		   'MDSYS',
		   'OEM_MONITOR',
		   'OLAPDBA',
		   'OLAPSVR',
		   'OLAPSYS',
		   'OLAP_DBA',
		   'ORDPLUGINS',
		   'ORDSYS',
		   'OSE$HTTP$ADMIN',
		   'RECOVERY_CATALOG_OWNER',
		   'TIMESERIES_DBA',
		   'TIMESERIES_DEVELOPER',
		   'TRACESVR',
		   'WKSYS',
		   'WKUSER',
		   'WKADMIN',
                   'PTRLADM',
		   'PUBLIC'
                 ) and grantee!=grantor;

spool off
cl bre
cl col
set lines 132 pages 22
undef hn

ed &&inst
